# maria db
spring.datasource.username=root
spring.datasource.password=mariadb
spring.datasource.url=jdbc:mariadb://localhost:3306/db_doj
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

# jpa db initialization strategy
spring.jpa.hibernate.ddl-auto=none

# print query to console
spring.jpa.properties.hibernate.show_sql=true
# format printed query
spring.jpa.properties.hibernate.format_sql=true
# print